<a href="https://colab.research.google.com/github/mokhivibes/ml_course_hometasks/blob/main/3_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Vazifa 1 — Array yaratish
'''np.zeros, np.ones, np.arange ishlatib quyidagilarni yarating:
5 ta noldan iborat array
3×3 birlardan iborat array
2 dan 20 gacha toq sonlar (qadam 2)
Har birining shape va dtype ni chiqaring.'''

import numpy as np

array = np.zeros(5)
print(array)
print(array.shape)
print(type(array))

array2 = np.ones((3, 3))
print(array2)
print(array2.shape)
print(type(array2))

toq_sonlar = np.arange(3, 20, 2)
print(toq_sonlar)
print(toq_sonlar.shape)
print(type(toq_sonlar))

[0. 0. 0. 0. 0.]
(5,)
<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
<class 'numpy.ndarray'>
[ 3  5  7  9 11 13 15 17 19]
(9,)
<class 'numpy.ndarray'>


In [ ]:
#Vazifa 2 — Array xususiyatlari
'''Quyidagi arrayni yarating:
arr = np.array([[4, 7, 2], [1, 9, 5], [8, 3, 6]])
shape, ndim, size, dtype ni chiqaring.
Natijalarni o'zingiz tushuntiring — har biri nima degani?'''

arr = np.array([[4, 7, 2],
                [1, 9, 5],
                [8, 3, 6]])
print("Shape:" , arr.shape, ", Number of dimension:", arr.ndim, ", Size:", arr.size, ", Type:", arr.dtype)


Shape: (3, 3) , Number of dimension: 2 , Size: 9 , Type: int64


In [ ]:
#Vazifa 3 — Indexing va Slicing
'''Yuqoridagi arr dan:
Birinchi qatorni oling
Ikkinchi ustunni oling
9 elementini indeks bilan oling
Yuqori o'ng 2×2 qismni oling'''

arr = np.array([[4, 7, 2],
                [1, 9, 5],
                [8, 3, 6]])
qator1 = arr[0]
print(qator1)

ustun2 = arr[0:3, 1]
print(ustun2)

element9 = arr[1, 1]
print(element9)

qism2x2 = arr[0:2, 1:3]
print(qism2x2)

[4 7 2]
[7 9 3]
9
[[7 2]
 [9 5]]


In [ ]:
#Vazifa 4 — Random
'''np.random.seed(42) ishlatib:
1 dan 100 gacha 10 ta tasodifiy butun son yarating
0 dan 1 gacha 3×3 float array yarating
Har ikkalasining mean va max ini chiqaring.'''

np.random.seed(42)
arr = np.random.randint(1, 100, 10)
print(arr)
print("Mean:", arr.mean(), "Max:", arr.max())

arr2 = np.random.rand(3, 3)
print(arr2)
print("Mean:",arr2.mean(), "Max:", arr2.max())

[52 93 15 72 61 21 83 87 75 75]
Mean: 63.4 Max: 93
[[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
Mean: 0.5084299233679132 Max: 0.9699098521619943


In [ ]:
#Vazifa 5 — 3D array
'''np.ones ishlatib 2×3×4 o'lchamli array yarating.
ndim, shape, size ni chiqaring va nima ekanligini tushuntiring
Birinchi 'qatlamdan' birinchi qatorni oling'''

array = np.ones((2,3,4))
print(array)
print(array.ndim, array.shape, array.size)
print(array[0, 0])

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3 (2, 3, 4) 24
[1. 1. 1. 1.]


In [ ]:
#Uyga vazifa:
'''1-vazifa:
NumPy: 20 ta sondan massiv yarating va statistikani hisoblang'''

array = np.random.randint(0, 21, 20)
print(array)
mean = array.mean()
maxi = array.max()
mini = array.min()
summ = array.sum()
shape = array.shape
size = array.size
standard = array.std()
print(mean)
print(maxi)
print(mini)
print(summ)
print(shape)
print(size)
print(standard)


[ 2 16  4 16 16 16  1  1  4  0  0 18  1 20 11  5  3 10 16  5]
8.25
20
0
165
(20,)
20
6.934515123640585


In [ ]:
# 2-vazifa: Pandas

'''o'zingiz haqingizda DataFrame yarating (kamida 5 ustun)'''

import pandas as pd
my_info = {"Ism": ["Moxichexra"],
            "Familiya": ["Usmonova"],
            "Yosh": [22],
            "Til":["O'zbek"],
            "Kurs": [3]}
table_info = pd.DataFrame(my_info)
print(table_info)


          Ism  Familiya  Yosh     Til  Kurs
0  Moxichexra  Usmonova    22  O'zbek     3


In [ ]:
#3-vazifa
'''CSV faylni o'qing va describe() natijasini tahlil qiling'''

data = pd.read_csv("/content/talabalar - talabalar.csv.csv")
print(data.describe())


             yosh        baho        kurs
count  100.000000  100.000000  100.000000
mean    22.600000   77.080000    2.420000
std      2.651472   13.786745    1.147505
min     18.000000   55.000000    1.000000
25%     20.750000   65.000000    1.000000
50%     23.000000   77.500000    2.000000
75%     25.000000   89.500000    3.250000
max     26.000000  100.000000    4.000000


In [ ]:
#4-vazifa
'''groupby() bilan bitta savol toping va javobini yozing'''
mean_ball = data.groupby("yosh")['baho'].mean()
print(mean_ball)


yosh
18    81.222222
19    75.000000
20    85.900000
21    72.357143
22    77.571429
23    73.916667
24    82.000000
25    73.416667
26    76.200000
Name: baho, dtype: float64


In [ ]:
#5-vazifa:
'''Kaggle bilan tanishib chiqing va dataset yuklab darsda o'rgangan
bilimlaringizni qo'llang'''

!pip install opendatasets

In [ ]:
import opendatasets as od
od.download("https://www.kaggle.com/datasets/aliyasaly1231/parental-genetics-and-child-trait-prediction-dataset/data")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: mokhivibes
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/aliyasaly1231/parental-genetics-and-child-trait-prediction-dataset


100%|██████████| 145k/145k [00:00<00:00, 25.6MB/s]

In [ ]:
import pandas as pd
df = pd.read_csv("/content/parental-genetics-and-child-trait-prediction-dataset/parental_genetics_child_traits.csv")
df.head(21)
df.describe()

,Father_Age,Mother_Age,Father_Height_cm,Mother_Height_cm,Predicted_Child_Height_cm
count,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000
mean,37.650286,34.035857,173.970257,161.084257,167.595814
std,10.323333,9.447972,6.922160,5.971471,8.816473
min,20.000000,18.000000,155.000000,145.000000,140.600000
25%,29.000000,26.000000,169.200000,157.000000,161.100000
50%,38.000000,34.000000,174.000000,161.100000,167.700000
75%,47.000000,42.000000,178.700000,165.200000,174.200000
max,55.000000,50.000000,197.900000,185.000000,198.500000


In [ ]:
print(f"Shape of data: >>>>>{df.shape}\n")
print(f"First 20 people's data: >>>>>{df.tail(20)}\n")
print(f"Types of data: >>>>>{df.dtypes}\n")
print(f"Size of data: >>>>>{df.size}\n")
moderates = df["Predicted_Health_Risk"] == "Moderate"
df_clean = df.dropna()
moderates = df_clean[df_clean["Predicted_Health_Risk"] == "Moderate"]

print(f"Only the data of people who have moderate predicted health risk: >>>>>{moderates}")
df.groupby("Family_ID")["Father_Age"].max()

Shape of data: >>>>>(7000, 18)

First 20 people's data: >>>>>     Family_ID  Father_Age  Mother_Age  Father_Height_cm  Mother_Height_cm  \
6980  FAM06981          45          43             168.7             159.9   
6981  FAM06982          53          25             181.6             156.8   
6982  FAM06983          26          39             170.4             161.8   
6983  FAM06984          47          42             175.0             155.7   
6984  FAM06985          47          29             180.4             153.9   
6985  FAM06986          33          26             167.2             157.7   
6986  FAM06987          23          27             166.4             150.7   
6987  FAM06988          37          27             191.6             168.2   
6988  FAM06989          44          26             168.0             164.1   
6989  FAM06990          26          43             185.3             155.8   
6990  FAM06991          47          44             173.6             157.9   
699

,Father_Age
Family_ID,
FAM00001,48
FAM00002,34
FAM00003,27
FAM00004,40
FAM00005,38
...,...
FAM06996,38
FAM06997,30
FAM06998,22
